Feature: Retrieve a vehicle by VIN and verify correct manufacture option codes values are being populated in the service response.


  Scenario Outline: Validate manufacture option codes information data returned by vds for a vin
    Given User wants to retrieve vin information for '<vin>'
    When User calls vds for vin
    Then User should see the manufacture option codes as '<optionCode>' in service response.
    # blank means there is no optionCode available
    Examples:
      | vin               | optionCode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | 1GC0KREG8KF231149 | 1SZ,1WT,4D7,5ST,8X2,9X2,A31,A91,AE7,AKO,AL0,AQQ,AU3,AXK,AY0,BG9,BWN,C67,CMD,DD8,DPN,E63,EF7,FE9,FHS,G80,GAZ,GEH,GT5,H2Q,I19,IOB,ITL,J95,JL1,K34,K47,KC4,KI4,KNP,KR1,KW5,L96,MAH,MYD,N33,NE8,NK5,NQG,NTB,NZ4,NZZ,PCM,PYN,QXT,R7N,R9N,SAF,SLM,TDM,TRW,U01,U2J,U73,UDC,UE0,UJM,UMN,UQ3,UVC,V22,V46,V76,V8D,VJH,VK3,VRK,VT7,VYU,WMK,X88,XL7,Z82,Z85,ZXT,ZY1                                                                                                                                                                                                                                                                                                                                                            |
      | 1G1PC5SB1E7428104 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | 5TFCZ5AN5LX215802 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | JTDKARFU9K3101964 | CP,FE,G_CF,G_CK,G_CN,G_P4,G_S6,LT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | 5TFUY5F18LX934832 | 2T,D5,FE,LB                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | WMWXP5C53K2H97916 | 1CA,1NA,205,249,255,258,2VB,313,322,346,382,3AG,402,423,430,431,450,473,494,4BD,4C1,4NE,4V9,507,521,534,544,550,563,5A1,5A4,645,655,674,6AC,6AE,785,823,842,845,850,853,8KL,8R9,8S4,8SM,8TN,925,927,992,9AA,Z67,Z8O,ZJ8,ZPP,ZSG,ZWI                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | 1GYS3AKJ1HR376297 | 1SA,1SZ,4AA,6ZC,7ZC,8X2,9X2,A31,A45,AG2,AKJ,AKK,AKO,AKX,AL0,AN3,AP9,ARL,AS8,ATH,ATV,AU3,AXP,AYQ,B30,B58,B85,BTM,BTV,BVE,C25,C49,C5Y,CE1,CJ4,D07,DCP,DD8,DL3,EF7,EPG,FHO,G1W,G80,GU5,H2X,I17,IO6,JD9,JF4,K34,K47,K4C,KA6,KB6,KC4,KI4,KNP,KRV,KW7,L86,M5U,MAH,N30,N38,NE8,NKC,NUF,NZD,QSS,R5A,R9N,RC4,ROO,RUF,SAF,SFE,SLM,TC2,TDM,TG5,U2K,U2L,U77,UDV,UE1,UFQ,UG1,UJM,UK3,UMN,UQH,UTJ,UVD,UVH,V54,V8D,VH9,VHM,VK3,VRK,VT7,VV4,WMH,XL7,YF5,YM8,Z75,Z82,Z95,ZY1                                                                                                                                                                                                                                                        |
      | 4S4BSANC4G3301760 | 23,X43,X6O,X7U,XAA,XN4,XN6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | 1N4BL3AP9HC274505 | 50S,BS2,E10,FL2,IKP,N11,ORG,SGD,TEC,USB,Z66                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | 2C4RC1AG3JR229313 | 0B6,0BF,170,1AA,27F,2DF,4EX,594,597,5I8,5N8,5PN,638,6US,875,894,938,AC5,APA,BAB,BCN,BHC,BHD,BHF,BNB,BNG,BRG,C1A,CAA,CEQ,CFX,CG3,CGU,CGY,CHF,CJ1,CJ5,CKA,CLA,CLB,CUC,CVU,CX8,CXC,CYY,DFH,ERF,GAE,GFA,GKB,GKD,GN9,GNA,GTS,GX3,GX4,GXM,GXU,GXX,H7XP,HAK,HBB,JAA,JAY,JB2,JB7,JCB,JFA,JHA,JHB,JJB,JJJ,JKA,JKP,JLP,JLV,JP3,JPB,JPG,JT5,LAH,LAL,LAQ,LAX,LAZ,LCD,LCS,LHD,LMA,LMK,MDA,MFS,ML2,MLD,MLF,MMP,MNA,MPK,MS9,MSN,NAS,NBU,NF1,NHA,NHB,NHJ,NHM,PTE,QTE,RAA,RCG,RD3,RF5,RF7,RF9,RFJ,RFP,RHJ,RS6,SBL,SCA,SDA,SUD,TBF,TMK,TZY,UAG,W7C,WFU,WLY,X81,X82,X83,X84,X85,X88,X89,X8L,X8P,X8U,X8W,X8X,X8Y,X8Z,X91,XAC,XAH,XAN,XBN,XC4,XCA,XFC,XFP,XGM,XH3,XJM,XKD,XKP,XLN,XPF,XRB,XS1,XXU,YAA,YEP,YGE,Z1A,ZAS,ZBD,ZNS,ZPD,XP,H7 |
      | 5XYP2DHC2LG039914 | CF,EB,STD,WK,WL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | JM3KFACM7J0312174 | 1TE,AE1,FOL,JCR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | 5NPE24AF1GH398763 | 01,CF,CN,MG,PE,WL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | MAJ3P1TE9JC199884 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |



